#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: travelmaker
    password: 1234

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 203551701f571bf408f7a5ead87437b9
            client-secret: lTm2Qya6pN9HfzjtZEL4eduTmobBL7Tv
            redirect-uri: http://localhost:10000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

  #jpa
  jpa:
    hibernate:
      ddl-auto: update #Entity와 DB 스키마 비교 후 수정 사항 반영(컬럼 추가)

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

  #Redis
  session:
    store-type: redis

  #multipart
  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 40MB
      file-size-threshold: 100MB


coolsms:
  api:
    key: "NCSAIGM8SGCYHUGE"
    secret: "IUDYW1NN4DROTS0VHS2IZLAC4GB77FZT"

